name: Build and Deploy Reporting App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Build Regnxt App
        run: |
          cd apps/reporting
          pnpm run build
        env:
          CI: false

      - name: Setup Distribution
        run: |
          # Create directory
          mkdir -p dist

          cp -r apps/reporting/dist/* dist/

          chmod -R 755 dist

          cat > dist/web.config << 'EOL'
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <rewrite>
                <rules>
                  <!-- SPA Routes -->
                  <rule name="SPA Routes" stopProcessing="true">
                    <match url=".*" />
                    <conditions logicalGrouping="MatchAll">
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                      <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="index.html" />
                  </rule>
                </rules>
              </rewrite>
              <handlers>
                <clear />
                <add name="StaticFile" path="*" verb="*" type="" modules="StaticFileModule,DefaultDocumentModule,DirectoryListingModule" scriptProcessor="" resourceType="Either" requireAccess="Read" allowPathInfo="false" preCondition="" responseBufferLimit="4194304" />
              </handlers>
              <staticContent>
                <remove fileExtension=".json" />
                <remove fileExtension=".woff" />
                <remove fileExtension=".woff2" />
                <remove fileExtension=".ttf" />
                <mimeMap fileExtension=".json" mimeType="application/json" />
                <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
                <mimeMap fileExtension=".woff2" mimeType="application/font-woff2" />
                <mimeMap fileExtension=".ttf" mimeType="application/x-font-ttf" />
              </staticContent>
              <defaultDocument enabled="true">
                <files>
                  <clear />
                  <add value="index.html" />
                </files>
              </defaultDocument>
              <httpProtocol>
                <customHeaders>
                  <remove name="X-Powered-By" />
                  <add name="Cache-Control" value="no-cache, no-store" />
                  <add name="Pragma" value="no-cache" />
                  <add name="Expires" value="-1" />
                </customHeaders>
              </httpProtocol>
            </system.webServer>
          </configuration>
          EOL

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: regnxt-app
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: regnxt-app

      - name: Deploy to Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "RegNxtPortalD"
          slot-name: "Production"
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E77D51FD04594742BD8C200FE54FDCDD }}
