name: Build and Deploy RegNXT Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      # Build both apps
      - name: Build Bird App
        run: |
          cd apps/bird
          pnpm run build
        env:
          CI: false

      - name: Build Reporting App
        run: |
          cd apps/reporting
          pnpm run build
        env:
          CI: false

      # Create combined dist directory
      - name: Setup Combined Distribution
        run: |
          # Create base directory with subdirectories
          mkdir -p combined-dist/bird
          mkdir -p combined-dist/reporting

          # Copy bird app files
          cp -r apps/bird/dist/* combined-dist/bird/

          # Copy reporting app files
          cp -r apps/reporting/dist/* combined-dist/reporting/

          # Set permissions
          chmod -R 755 combined-dist

          # Create web.config
          cat > combined-dist/web.config << 'EOL'
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <rewrite>
                <rules>
                  <!-- Default route -->
                  <rule name="Default Route" stopProcessing="true">
                    <match url="^$" />
                    <action type="Redirect" url="bird" redirectType="Permanent" />
                  </rule>

                  <!-- Bird SPA -->
                  <rule name="Bird SPA" stopProcessing="true">
                    <match url="^bird" />
                    <action type="Rewrite" url="bird/index.html" />
                    <conditions>
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                      <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                    </conditions>
                  </rule>

                  <!-- Reporting SPA -->
                  <rule name="Reporting SPA" stopProcessing="true">
                    <match url="^reporting" />
                    <action type="Rewrite" url="reporting/index.html" />
                    <conditions>
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                      <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                    </conditions>
                  </rule>
                </rules>
              </rewrite>
              <handlers>
                <clear />
                <add name="StaticFile" path="*" verb="*" type="" modules="StaticFileModule,DefaultDocumentModule,DirectoryListingModule" scriptProcessor="" resourceType="Either" requireAccess="Read" allowPathInfo="false" preCondition="" responseBufferLimit="4194304" />
              </handlers>
              <staticContent>
                <remove fileExtension=".json" />
                <remove fileExtension=".woff" />
                <remove fileExtension=".woff2" />
                <remove fileExtension=".ttf" />
                <mimeMap fileExtension=".json" mimeType="application/json" />
                <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
                <mimeMap fileExtension=".woff2" mimeType="application/font-woff2" />
                <mimeMap fileExtension=".ttf" mimeType="application/x-font-ttf" />
              </staticContent>
              <defaultDocument enabled="true">
                <files>
                  <clear />
                  <add value="index.html" />
                </files>
              </defaultDocument>
              <httpProtocol>
                <customHeaders>
                  <remove name="X-Powered-By" />
                  <add name="Cache-Control" value="no-cache, no-store" />
                  <add name="Pragma" value="no-cache" />
                  <add name="Expires" value="-1" />
                </customHeaders>
              </httpProtocol>
            </system.webServer>
            <location path="bird">
              <system.webServer>
                <defaultDocument>
                  <files>
                    <clear />
                    <add value="index.html" />
                  </files>
                </defaultDocument>
              </system.webServer>
            </location>
            <location path="reporting">
              <system.webServer>
                <defaultDocument>
                  <files>
                    <clear />
                    <add value="index.html" />
                  </files>
                </defaultDocument>
              </system.webServer>
            </location>
          </configuration>
          EOL

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: combined-apps
          path: combined-dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: combined-apps

      - name: Deploy to Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "RegNxtPortalD"
          slot-name: "Production"
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E77D51FD04594742BD8C200FE54FDCDD }}
