name: Build and deploy Node.js app to Azure Web App - RegNxtPortalD
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "pnpm"
          
      - name: Install Dependencies
        run: pnpm install
        
      - name: Build Regnxt App
        run: |
          cd apps/regnxt
          pnpm run build
        env:
          CI: false
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_FAST_API_BACKEND: ${{ secrets.VITE_FAST_API_BACKEND }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: regnxt-app
          path: apps/regnxt/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: regnxt-app
          
      - name: Deploy to Azure
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "RegNxtPortalD"
          slot-name: "Production"
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E77D51FD04594742BD8C200FE54FDCDD }}