name: Build and Deploy RegNXT Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      # Build both apps
      - name: Build Bird App
        run: |
          cd apps/bird
          pnpm run build
        env:
          CI: false

      - name: Build Reporting App
        run: |
          cd apps/reporting
          pnpm run build
        env:
          CI: false

      # Create combined dist directory with proper structure
      - name: Setup Combined Distribution
        run: |
          # Create base directory
          mkdir -p combined-dist

          # Copy bird app files to the root (since it's the default app)
          cp -r apps/bird/dist/* combined-dist/

          # Create and copy reporting app
          mkdir -p combined-dist/reporting
          cp -r apps/reporting/dist/* combined-dist/reporting/

          # Create web.config
          cat > combined-dist/web.config << 'EOL'
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <rewrite>
                <rules>
                  <!-- Default route -->
                  <rule name="Default" stopProcessing="true">
                    <match url="^$" />
                    <action type="Rewrite" url="index.html" />
                  </rule>

                  <!-- Reporting app routes -->
                  <rule name="Reporting SPA Routes" stopProcessing="true">
                    <match url="^reporting/.*" />
                    <conditions>
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                      <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="reporting/index.html" />
                  </rule>

                  <!-- Main app routes (catch-all) -->
                  <rule name="SPA Routes" stopProcessing="true">
                    <match url=".*" />
                    <conditions>
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                      <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="index.html" />
                  </rule>
                </rules>
              </rewrite>
              <staticContent>
                <mimeMap fileExtension=".js" mimeType="application/javascript" />
                <mimeMap fileExtension=".json" mimeType="application/json" />
                <mimeMap fileExtension=".wasm" mimeType="application/wasm" />
                <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
                <mimeMap fileExtension=".woff2" mimeType="application/font-woff2" />
                <mimeMap fileExtension=".ttf" mimeType="application/font-ttf" />
              </staticContent>
              <httpProtocol>
                <customHeaders>
                  <add name="Cache-Control" value="no-cache, no-store" />
                  <add name="Pragma" value="no-cache" />
                  <add name="Expires" value="-1" />
                </customHeaders>
              </httpProtocol>
            </system.webServer>
          </configuration>
          EOL

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: "RegNxtPortalD"
          slot-name: "Production"
          package: combined-dist
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_044585DFA9D24C99ACAB8C0FAED7E995 }}
